apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jnbj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jnbj
    app.kubernetes.io/part-of: byoc-app-yqao
  name: jnbjp0aj
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: jnbj
    weight: null
status: {}
